name: Build React Native APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Dependencies
        run: npm install

      - name: Give Gradle Permission
        run: chmod +x android/gradlew

      - name: Generate Release APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-native-apk
          path: android/app/build/outputs/apk/release/app-release.apk
