name: Build APK And Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle Cache
        uses: gradle/actions/setup-gradle@v4

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Dependencies
        run: npm ci

      - name: Grant Gradle Permission
        run: chmod +x android/gradlew

      - name: Build Release APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Find APK
        run: |
          APK_FILE=$(find android/app/build/outputs/apk -name "*.apk" | head -n 1)

          echo "APK_FILE=$APK_FILE" >> $GITHUB_ENV

          echo "Found APK:"
          echo "$APK_FILE"

      - name: Create GitHub Release And Upload APK
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.APK_FILE }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.BUILD_REPO_TOKEN }}
