name: Build APK And Publish

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle Cache
        uses: gradle/actions/setup-gradle@v4

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Dependencies
        run: npm ci

      - name: Gradle Permission
        run: chmod +x android/gradlew

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Clone Public Repo
        run: |
          git clone https://x-access-token:${{ secrets.BUILD_REPO_TOKEN }}@github.com/hemantcomfygen/react-native-app-build.git

      - name: Read App Info
        run: |
          echo "APP_NAME=$(node -p "require('./package.json').name")" >> $GITHUB_ENV

      - name: Copy APK
        run: |
          mkdir -p react-native-app-build/releases/${GITHUB_REF_NAME}
          cp android/app/build/outputs/apk/release/app-arm64-v8a-release.apk \
          react-native-app-build/releases/${GITHUB_REF_NAME}/${APP_NAME}-${GITHUB_REF_NAME}.apk

      - name: Commit APK
        run: |
          cd react-native-app-build

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .

          git commit -m "Release ${GITHUB_REF_NAME}" || true

          git push
